### ISSUE TITLE
unknown url type

### ISSUE THREAD

**Issue by takiskan** [luizmlo/Py-Lightshot-Dowloader#1]
### some weeks ago it used to be working fine, but now it when you try to run it it says : 
Traceback (most recent call last):
  File "LightLoader.py", line 60, in <module>
    generateImgur(url, fileName)
  File "LightLoader.py", line 43, in generateImgur
    urlretrieve(imgUrl, pathArquivo)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 510, in open
    req = Request(fullurl, data)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 328, in __init__
    self.full_url = url
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 354, in full_url
    self._parse()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '//st.prntscr.com/2017/09/07/1522/img/0_173a7b_211be8ff.png'

**Comment by luizmlo** [comment]
Fixed it, try it now.
